### ISSUE TITLE
render preview image in fluid template

### ISSUE THREAD

**Issue by Karionis** [sksksksk/skvideo#5]
Hello, first of all thank you for your work with this extension!

My suggestion: The img tag for preview image is rendered by the extension code, not in the fluid template and not by the standard fluid image view helper. Therefore it is not possible to customize the rendering of the image, e. g. in order to render a responsive image tag with sources for different browser widths or to add a lazyload attribute. It would be nice to have more control over the rending of the preview image tag.

Karionis

**Comment by heisenbol** [comment]
I understand your requirement, but it is not easy to decouple the fetching of the image with the generation of the img tag. It needs to go through a viewhelper in order to make sure that the preview image is first fetched, and then the img tag is generated.

But I will take a look into it. Maybe I'll come up with something.

**Comment by heisenbol** [comment]
The generation of the markup has been moved to the fluid template now (commit 6d0da90 ). This will be included in the next release

**Comment by Karionis** [comment]
Great! Thank you!
